services:
    CleverAge\ProcessBundle\Registry\ProcessConfigurationRegistry:
        public: false
        arguments:
            - ~

    CleverAge\ProcessBundle\Registry\TransformerRegistry:
        public: false
