services:
    cleverage_process.transformer.mapping:
        class: CleverAge\ProcessBundle\Transformer\MappingTransformer
        arguments:
            - '@property_accessor'
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.slugify:
        class: CleverAge\ProcessBundle\Transformer\SlugifyTransformer
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.explode:
        class: CleverAge\ProcessBundle\Transformer\ExplodeTransformer
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.trim:
        class: CleverAge\ProcessBundle\Transformer\TrimTransformer
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.array_map:
        class: CleverAge\ProcessBundle\Transformer\ArrayMapTransformer
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.array_first:
        class: CleverAge\ProcessBundle\Transformer\ArrayFirstTransformer
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.property_accessor:
        class: CleverAge\ProcessBundle\Transformer\PropertyAccessorTransformer
        arguments:
            - '@property_accessor'
        tags:
            - { name: cleverage.transformer }
